version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - ReesMorris
    assignees:
      - ReesMorris
    registries:
      - npm-registry-npm-fontawesome-com
